let express = require("express")
let cors = require("cors")
let mongoose = require("mongoose")
const route = require("./routes/route")
let app = express()
app.use(express.json())
app.use(cors())
mongoose.connect("mongodb://127.0.0.1:27017/mern-book").then(()=>{console.log("ok")}).catch((err)=>{console.log(err)})

app.use("/",route)
app.listen(5000)